web:
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - postgis:postgis
  volumes:
    - /cis-esp/static
  env_file: .env
  environment:
    - POSTGRES_HOST=postgis

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

postgis:
  restart: always
  image: mdillon/postgis:latest
  ports:
    - "5432"
  volumes:
    - pgdata:/var/lib/postgresql/data/
  env_file: .env
